"""Production-shaped fund-flow guard fixtures for graph-path tests."""
from __future__ import annotations

from typing import Any

from tradingagents.dataflows.fund_flow_evidence import (
    build_consensus_evidence,
    build_sina_evidence,
    select_fund_flow_source,
    validate_model_summary,
)

_SYMBOL = "600519"
_AS_OF = "2026-08-13"


def _new_algorithm_records(field: str, values: tuple[str, str]) -> list[dict[str, Any]]:
    """Build aligned records that the production consensus builder can accept."""
    return [
        {
            "source": source,
            "algorithm_group": "new_algorithm_group",
            "automated_consensus_eligible": True,
            "status": "available",
            "symbol": _SYMBOL,
            "date": _AS_OF,
            "period_kind": "historical_daily",
            "time_window": "1d",
            "field": field,
            "value": value,
            "field_semantics": {
                field: "主力净额（负值表示净流出）"
                if field == "r0_net"
                else "总净额（负值表示净流出）"
            },
            "unit": "亿元",
        }
        for source, value in zip(("sina_app", "eastmoney"), values)
    ]


def _validation_records() -> list[dict[str, Any]]:
    """Build five single-source daily records for validation's not_checked path."""
    rows = [
        {
            "opendate": f"2026-08-{day:02d}",
            "netamount": "100000000",
            "r0_net": "100000000",
        }
        for day in range(9, 14)
    ]
    return build_sina_evidence(
        rows,
        symbol=_SYMBOL,
        requested_as_of=_AS_OF,
        retrieved_at=None,
    )


def _guard_from_production_outputs(
    consensus: dict[str, Any],
    validation: dict[str, Any],
) -> dict[str, Any]:
    """Assemble the same guard envelope and fail-closed predicate as production."""
    blocked = bool(
        not isinstance(consensus, dict)
        or consensus.get("status") not in {"selected", "consensus"}
        or not consensus.get("direction_allowed")
        or consensus.get("hard_guard", {}).get("blocked")
        or validation.get("status") in {"blocked", "mismatch"}
        or validation.get("hard_guard", {}).get("blocked")
    )
    reason = (
        validation.get("hard_guard", {}).get("reason")
        or consensus.get("reason", "fund-flow consensus unavailable")
    )
    return {
        "blocked": blocked,
        "direction_allowed": not blocked,
        "status": consensus.get("status", "not_checked"),
        "consensus": consensus,
        "validation": validation,
        "reason": reason,
    }


def valid_fund_flow_consensus_guard() -> dict[str, Any]:
    """Return a fresh allow guard generated by production evidence builders."""
    consensus = build_consensus_evidence(
        _new_algorithm_records("r0_net", ("1.0", "1.1")),
        symbol=_SYMBOL,
        requested_as_of=_AS_OF,
        field="r0_net",
    )
    validation = validate_model_summary(_validation_records(), model_text=None)
    return _guard_from_production_outputs(consensus, validation)


def single_source_fund_flow_selection_guard() -> dict[str, Any]:
    """Return an allow guard for exactly one valid new-algorithm source."""
    records = _new_algorithm_records("r0_net", ("1.0", "1.1"))[:1]
    selection = select_fund_flow_source(
        records,
        symbol=_SYMBOL,
        requested_as_of=_AS_OF,
    )
    validation = validate_model_summary(
        records,
        model_text=None,
        selected_field=selection.get("selected_field"),
    )
    return _guard_from_production_outputs(selection, validation)


def blocked_fund_flow_consensus_guard() -> dict[str, Any]:
    """Return a production-shaped guard for an unexplained source conflict."""
    consensus = build_consensus_evidence(
        _new_algorithm_records("r0_net", ("1.0", "10.0")),
        symbol=_SYMBOL,
        requested_as_of=_AS_OF,
        field="r0_net",
    )
    validation = validate_model_summary(_validation_records(), model_text=None)
    return _guard_from_production_outputs(consensus, validation)


def mismatched_fund_flow_consensus_guard() -> dict[str, Any]:
    """Return a valid consensus with a production-generated validation mismatch."""
    consensus = build_consensus_evidence(
        _new_algorithm_records("r0_net", ("1.0", "1.1")),
        symbol=_SYMBOL,
        requested_as_of=_AS_OF,
        field="r0_net",
    )
    validation = validate_model_summary(
        _validation_records(),
        model_text="5日累计：主力净流入 999 亿。",
    )
    return _guard_from_production_outputs(consensus, validation)


def direction_disallowed_fund_flow_consensus_guard() -> dict[str, Any]:
    """Return a production-shaped non-main-force guard with direction blocked."""
    consensus = build_consensus_evidence(
        _new_algorithm_records("netamount", ("1.0", "1.1")),
        symbol=_SYMBOL,
        requested_as_of=_AS_OF,
        field="netamount",
    )
    validation = validate_model_summary(_validation_records(), model_text=None)
    return _guard_from_production_outputs(consensus, validation)
